name: Deploy to Uberspace
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy using Rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avrh --delete --exclude=".git" --exclude=".github" --exclude='.env'
          path: /
          remote_path: /var/www/virtual/${{ vars.SSH_USERNAME }}/app
          remote_host: ${{ vars.SSH_HOST }}
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Save SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key
          chmod 600 deploy_key
      - name: Run post-deploy commands on server
        run: |
          ssh -o StrictHostKeyChecking=no -i ./deploy_key ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} << 'EOF'
            cd /var/www/virtual/${{ vars.SSH_USERNAME }}/app
            touch database/database.sqlite
            composer install --no-interaction --prefer-dist --no-dev
            npm install
            npm run build
            php artisan migrate:fresh
            php artisan storage:link
          EOF
